export interface ModuleInfo {
  slug: string;
  order: number;
  navTitle: string;
  icon: string;
  badge: string;
  heroTitle: string;
  tagline: string;
  features: string[];
}

export const MODULES: ModuleInfo[] = [
  {
    slug: 'employees',
    order: 1,
    navTitle: 'Employees Management',
    icon: 'users',
    badge: 'EMPLOYEES',
    heroTitle: 'Comprehensive Employee Profiles',
    tagline: "Manage employee's personal and financial information, documents, assets, and company structure.",
    features: [
      'Comprehensive employee profiles',
      'Organization structures, visualized',
      'Multi levels — country, company, currency',
      'People HR letters management, HR documentation',
      'Keep an eye on important employee metrics',
      'HR operation automation',
      'View different types of organization structure',
      'Assets management',
      'Customized reports',
    ],
  },
  {
    slug: 'payroll',
    order: 2,
    navTitle: 'Payroll Management',
    icon: 'wallet',
    badge: 'PAYROLL',
    heroTitle: 'Complicated Payroll, Simplified',
    tagline: "Run your salaries calculation and your personnel affairs according to your company's policies and procedures. A seamless way of running your day-to-day operations.",
    features: [
      'Complicated payroll and personnel operations',
      'Dynamic social security & TAX management',
      'Day to day operation transactions',
      'Salary scale management',
      'Formula based payroll',
      'Leave & overtime management',
      'Compensation and benefits management',
      'Systematic employee management',
      'End of service management',
      'Disciplinary action module',
      'Multi-currency & ERP integration',
      'Customized reports',
    ],
  },
  {
    slug: 'self-service',
    order: 3,
    navTitle: 'Self Service & Mobile App',
    icon: 'smartphone',
    badge: 'SELF SERVICE',
    heroTitle: 'Empower Every Employee',
    tagline: 'A collaborative cloud managers self-service (MSS) and employee self-service (ESS) solution to track HR operations and progress by keeping managers and employees connected, up-to-date, and informed through cutting edge technology.',
    features: [
      'Social HR platform',
      'Employee engagement, automate employee requests',
      'Electronic pay slip distribution',
      'Workflow approvals',
      'Check your leave balances',
      'Announcement management',
      'Information update process',
      'Automated notifications',
      'Check in for attendance through your mobile, wherever you are, using GPS & Geofence features',
    ],
  },
  {
    slug: 'attendance',
    order: 4,
    navTitle: 'Time Attendance',
    icon: 'clock',
    badge: 'TIME & ATTENDANCE',
    heroTitle: 'Smart Attendance Management',
    tagline: 'Track, analyze, and manage attendance while saving time and effort to run bigger operations.',
    features: [
      'Manage employee attendance',
      'Plan employee schedule with roster shift',
      'Apply automatic shift rules',
      'Issuing transactions linked to payroll',
      'Managing split and flexible shifts',
      'Multi-shifts, parameterized',
      'Geolocation tracking',
      'Workflows for approval',
      'Integrated with all TA machines',
      'Attendance data analysis',
    ],
  },
  {
    slug: 'business-trip',
    order: 5,
    navTitle: 'Business Trip Management',
    icon: 'plane',
    badge: 'BUSINESS TRIP',
    heroTitle: 'Simplify Every Business Trip',
    tagline: 'Give employees and managers full visibility into travel — from request to reimbursement.',
    features: [
      'Online trip requests & manager approvals',
      'Trip budget and expense tracking',
      'Itinerary and travel details in one place',
      'Real-time trip status and reporting',
    ],
  },
  {
    slug: 'performance',
    order: 6,
    navTitle: 'Performance Appraisal',
    icon: 'clipboardCheck',
    badge: 'PERFORMANCE',
    heroTitle: 'Evaluate, Reward, and Grow',
    tagline: 'Our system customizes evaluations, tracks goals, offers feedback, supports pay-for-performance, and provides analytical reports.',
    features: [
      'Customized evaluation process',
      'Design your own appraisal cycle',
      'Performance appraisal surveys',
      'Self-appraisal evaluation',
      'Evaluate employees on planned targets and objectives',
      'Keep your employees engaged',
      'Pay for performance',
      'Comprehensive analytical reports',
    ],
  },
  {
    slug: 'talent-development',
    order: 7,
    navTitle: 'Talent Development',
    icon: 'graduationCap',
    badge: 'TALENT DEVELOPMENT',
    heroTitle: 'Develop Your Talent',
    tagline: 'Our system analyzes competency gaps, manages training, and automates feedback.',
    features: [
      'Competency gap analysis',
      'Develop employee skills & competencies',
      'Human capital management',
      'Organize training courses',
      'Training calendar and dashboards',
      'Automated feedback with training surveys',
      'Training planning and budgeting',
      'Training registration management',
      'Training cost analysis',
    ],
  },
  {
    slug: 'talent-acquisition',
    order: 8,
    navTitle: 'Talent Acquisition',
    icon: 'search',
    badge: 'TALENT ACQUISITION',
    heroTitle: 'Hire the Right People, Faster',
    tagline: 'Our platform simplifies job posting, interview scheduling, and offers customization for career sites. It also digitizes applicant interviews.',
    features: [
      'Job posting & pipeline management',
      'Easy interview scheduling',
      'Send emails in bulk',
      'Customize your career site',
      'Digitize interviews with applicants',
      'Automate job offers',
    ],
  },
  {
    slug: 'career-path',
    order: 9,
    navTitle: 'Career Path Planning',
    icon: 'trendingUp',
    badge: 'CAREER PATHING',
    heroTitle: 'Build Careers, Not Just Jobs',
    tagline: 'Our system sets career paths, qualifications, and goals, combines assessments with planning, tracks progress, and identifies promotable employees.',
    features: [
      'Set the possible career paths for each career goal',
      'Set job qualification requirements',
      'Competency-based career path',
      'Combine employee assessments with career path planning',
      "Let employees choose their ultimate career goal",
      'Get training recommendations to help employees progress',
      'Track employee progress toward their career goal',
      "Know who's ready for a promotion",
    ],
  },
  {
    slug: 'succession-planning',
    order: 10,
    navTitle: 'Succession Planning',
    icon: 'userCheck',
    badge: 'SUCCESSION PLANNING',
    heroTitle: "Plan for What's Next",
    tagline: 'We identify key positions, successors, job requirements, evaluate candidates, assess employee readiness, and provide successor training.',
    features: [
      'Identifying key positions & create key positions list',
      'Identifying the successor or successors',
      'Identifying job requirements and evaluate',
      'Search for candidates who best match the key positions requirements',
      'Assess employee readiness',
      'Find trainings to prepare the successors',
    ],
  },
];
